dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - webdriver-manager update --versions.chrome 84.0.4147.30
  - google-chrome --version
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriverUpdate=false